name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8.0.332+9
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml jacoco:report

      - name: Coveralls
        run: mvn -B --file pom.xml coveralls:report --define repoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
